---
version: "3.8"
services:
  ################################################################
  # Postgresql database
  ################################################################
  postgres:
    image: postgres:14.5-alpine3.16
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .production.env
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=POSTGRES]
      restart_policy:
        condition: on-failure

  ################################################################
  # Tus file uploads server
  ################################################################
  tusd:
    image: tackboon97/tusd:sha-e0189d1
    hostname: tusd
    ports:
      - "1080:1080"
    volumes:
      - tusd-data:/srv/tusd-data/data
    command: ["--hooks-grpc", "cm-catalogue-file-grpc:5000"]
    depends_on:
      - cm-catalogue-file-grpc
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=TUSD]
      restart_policy:
        condition: on-failure

  ################################################################
  # Static file server
  ################################################################
  nginx:
    image: nginx:1.23.1
    hostname: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api/openapi/:/usr/share/nginx/yaml/openapi:ro
      - nginx-log:/var/log/nginx
    depends_on:
      - cm-catalogue-http
      - cm-customer-http
      - cm-user-http
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=NGINX]
      restart_policy:
        condition: on-failure

  ################################################################
  # Web base frontend for application
  ################################################################
  cm-web:
    image: tackboon97/cm-catalogue-web
    hostname: cm-web
    ports:
      - "3000:80"
    env_file:
      - .production.env
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=WEB]
      restart_policy:
        condition: on-failure

  ################################################################
  # Application service - user (HTTP Protocol)
  ################################################################
  cm-user-http:
    image: tackboon97/cm-catalogue-user
    hostname: cm-user-http
    volumes:
      - ./service-account-file.json:${SERVICE_ACCOUNT_FILE}
    env_file:
      - .production.env
    environment:
      - "PORT=5000"
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=USER_HTTP_API]
      restart_policy:
        condition: on-failure

  ################################################################
  # Application service - customer (HTTP Protocol)
  ################################################################
  cm-customer-http:
    image: tackboon97/cm-catalogue-customer
    hostname: cm-customer-http
    volumes:
      - ./service-account-file.json:${SERVICE_ACCOUNT_FILE}
    env_file:
      - .production.env
    environment:
      - "PORT=5000"
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=CUSTOMER_HTTP_API]
      restart_policy:
        condition: on-failure

  ################################################################
  # Application service - catalogue (HTTP Protocol)
  ################################################################
  cm-catalogue-http:
    image: tackboon97/cm-catalogue-catalogue
    hostname: cm-catalogue-http
    volumes:
      - ./service-account-file.json:${SERVICE_ACCOUNT_FILE}
    env_file:
      - .production.env
    environment:
      - "PORT=5000"
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=CATALOGUE_HTTP_API]
      restart_policy:
        condition: on-failure

  ################################################################
  # Application service - catalogue-file (GRPC Protocol)
  ################################################################
  cm-catalogue-file-grpc:
    image: tackboon97/cm-catalogue-catalogue-file
    hostname: cm-catalogue-file-grpc
    volumes:
      - ./service-account-file.json:${SERVICE_ACCOUNT_FILE}
    ports:
      - "5000:5000"
    env_file:
      - .production.env
    environment:
      - "PORT=5000"
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=CATALOGUE_FILE_GRPC_API]
      restart_policy:
        condition: on-failure

volumes:
  postgres-data:
  tusd-data:
  nginx-log: