name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Build the Docker images
      run: ./scripts/build_docker.sh $(date +%s)
    - name: List docker image
      run:  docker image ls
    - name: Dockerhub login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: push to Dockerhub
      run: ./push_docker.sh $(date +%s)